### ISSUE TITLE
Issue starting Betty

### ISSUE THREAD

**Issue by ndsteve** [SamyPesse/betty#11]
Really excited to try Betty out!  I'm getting an error when installing on a fresh install of Centos 7.  I set the TWILIO_SID, TWILIO_TOKEN and TWILIO_APPID variables along with the TEAM variable.  Any idea what's causing this error?
```
[root@CENTOS7 ~]# betty

/usr/local/lib/node_modules/betty-cli/node_modules/cookie-session/index.js:40
  if (!keys && opts.signed) throw new Error('.keys required.');
                                  ^
Error: .keys required.
    at module.exports (/usr/local/lib/node_modules/betty-cli/node_modules/cookie-session/index.js:40:35)
    at Object.<anonymous> (/usr/local/lib/node_modules/betty-cli/lib/index.js:21:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/betty-cli/betty.js:3:13)
    at Module._compile (module.js:456:26)
```

**Comment by ndsteve** [comment]
Needed to set the SECRET token.  Everything is working now!
