### ISSUE TITLE
SMS Forwarding

### ISSUE THREAD

**Issue by melaleuca5** [SamyPesse/betty#19]
When a SMS is being forward and you reply to the msg to start the conversation it says "Sorry, I did not understand your message.

**Comment by melaleuca5** [comment]
If I try Betty: Call +Number I see the following error in the console 

- [30/May/2015:23:00:39 +0000] "POST /twiml/sms HTTP/1.1" 400 80 "-" "TwilioProxy/1.1"
Error: Error: Not Found
    at app.use.res.status.send.error (/root/test/betty/lib/index.js:47:13)
    at Layer.handle [as handle_request] (/root/test/betty/node_modules/express/lib/router/layer.js:82:5)
    at trim_prefix (/root/test/betty/node_modules/express/lib/router/index.js:302:13)
    at /root/test/betty/node_modules/express/lib/router/index.js:270:7
    at Function.proto.process_params (/root/test/betty/node_modules/express/lib/router/index.js:321:12)
    at next (/root/test/betty/node_modules/express/lib/router/index.js:261:10)
    at jsonParser (/root/test/betty/node_modules/body-parser/lib/types/json.js:89:44)
    at Layer.handle [as handle_request] (/root/test/betty/node_modules/express/lib/router/layer.js:82:5)
    at trim_prefix (/root/test/betty/node_modules/express/lib/router/index.js:302:13)
    at /root/test/betty/node_modules/express/lib/router/index.js:270:7
